export function Request(acctId) {
    return {
        Version: '01.00',
        MessageType: 'RentalStationList',
    };
}

export function Response() {
    return {
        ResultCode: '1000',
        ResultMessage: 'success',
        TransactionDateTime: '20201229111132',
        RentalStationListResponse: [
            {
                CityCode: '01',
                CityName: '台北',
                StationInformation: [
                    {
                        StationCode: '36-219',
                        StationName: '台北松山機場站',
                        StationTelephone: '02-2715-1133',
                        StationAddress: '10548 台北市松山區敦化北路340之9號',
                        StationType: '2',
                        Latitude: '25.061978',
                        Longitude: '121.551995',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1930',
                        },
                    },
                    {
                        StationCode: '1-201',
                        StationName: '台北建北站',
                        StationTelephone: '02-2502-1389',
                        StationAddress: '10489 台北市中山區建國北路一段71-1號',
                        StationType: '2',
                        Latitude: '25.051158',
                        Longitude: '121.537153',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '104-210',
                        StationName: '台北車站(機捷A1)',
                        StationTelephone: '02-2515-9393',
                        StationAddress: '10349 台北市大同區鄭州路8號B1',
                        StationType: '2',
                        Latitude: '25.048722',
                        Longitude: '121.514227',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '1000',
                            EndTime: '1900',
                        },
                    },
                    {
                        StationCode: '2-202',
                        StationName: '台北忠孝站',
                        StationTelephone: '02-8785-6620',
                        StationAddress: '11062 台北市信義區忠孝東路五段705號',
                        StationType: '2',
                        Latitude: '25.042513',
                        Longitude: '121.580242',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '3-203',
                        StationName: '台北景美站',
                        StationTelephone: '02-8931-0266',
                        StationAddress: '11681 台北市文山區羅斯福路五段221號',
                        StationType: '2',
                        Latitude: '25.002065',
                        Longitude: '121.539165',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '4-204',
                        StationName: '台北士林站',
                        StationTelephone: '02-2835-1100',
                        StationAddress: '11158 台北市士林區德行西路81號',
                        StationType: '2',
                        Latitude: '25.104611',
                        Longitude: '121.521735',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '60-222',
                        StationName: '台北淡水站',
                        StationTelephone: '02-2629-9393',
                        StationAddress: '25155 新北市淡水區中正路1號',
                        StationType: '2',
                        Latitude: '25.174878',
                        Longitude: '121.432739',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '44-205',
                        StationName: '台北內湖站',
                        StationTelephone: '02-2658-3366',
                        StationAddress: '11493 台北市內湖區內湖路一段236號',
                        StationType: '2',
                        Latitude: '25.082302',
                        Longitude: '121.565174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '52-206',
                        StationName: '台北南港站',
                        StationTelephone: '02-2651-1333',
                        StationAddress: '11568 台北市南港區經貿一路59號',
                        StationType: '2',
                        Latitude: '25.056168',
                        Longitude: '121.620091',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '85-208',
                        StationName: '台北新店站',
                        StationTelephone: '02-2915-3311',
                        StationAddress: '23143 新北市新店區北新路二段45號',
                        StationType: '2',
                        Latitude: '24.972855',
                        Longitude: '121.542796',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '115-905',
                        StationName: '台北板橋驛站',
                        StationTelephone: '02-2250-3131',
                        StationAddress: '220 新北市板橋區文化路二段266號',
                        StationType: '2',
                        Latitude: '25.028858',
                        Longitude: '121.471619',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '87-218',
                        StationName: '台北中和站',
                        StationTelephone: '02-2242-3232',
                        StationAddress: '23553 新北市中和區連城路126號',
                        StationType: '2',
                        Latitude: '24.999440',
                        Longitude: '121.495982',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '48-213',
                        StationName: '台北新莊站',
                        StationTelephone: '02-2906-7711',
                        StationAddress: '24257 新北市新莊區中正路527號',
                        StationType: '2',
                        Latitude: '25.033227',
                        Longitude: '121.439553',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '64-216',
                        StationName: '台北蘆洲站',
                        StationTelephone: '02-2285-2299',
                        StationAddress: '24760 新北市蘆洲區三民路88號',
                        StationType: '2',
                        Latitude: '25.085329',
                        Longitude: '121.473834',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '73-217',
                        StationName: '台北土城站',
                        StationTelephone: '02-2269-3131',
                        StationAddress: '23680 新北市土城區中央路三段158號',
                        StationType: '2',
                        Latitude: '24.965791',
                        Longitude: '121.432121',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                ],
            },
            {
                CityCode: '02',
                CityName: '新北市',
                StationInformation: [
                    {
                        StationCode: '36-219',
                        StationName: '台北松山機場站',
                        StationTelephone: '02-2715-1133',
                        StationAddress: '10548 台北市松山區敦化北路340之9號',
                        StationType: '2',
                        Latitude: '25.061978',
                        Longitude: '121.551995',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1930',
                        },
                    },
                    {
                        StationCode: '1-201',
                        StationName: '台北建北站',
                        StationTelephone: '02-2502-1389',
                        StationAddress: '10489 台北市中山區建國北路一段71-1號',
                        StationType: '2',
                        Latitude: '25.051158',
                        Longitude: '121.537153',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '2-202',
                        StationName: '台北忠孝站',
                        StationTelephone: '02-8785-6620',
                        StationAddress: '11062 台北市信義區忠孝東路五段705號',
                        StationType: '2',
                        Latitude: '25.042513',
                        Longitude: '121.580242',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '3-203',
                        StationName: '台北景美站',
                        StationTelephone: '02-8931-0266',
                        StationAddress: '11681 台北市文山區羅斯福路五段221號',
                        StationType: '2',
                        Latitude: '25.002065',
                        Longitude: '121.539165',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '4-204',
                        StationName: '台北士林站',
                        StationTelephone: '02-2835-1100',
                        StationAddress: '11158 台北市士林區德行西路81號',
                        StationType: '2',
                        Latitude: '25.104611',
                        Longitude: '121.521735',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '60-222',
                        StationName: '台北淡水站',
                        StationTelephone: '02-2629-9393',
                        StationAddress: '25155 新北市淡水區中正路1號',
                        StationType: '2',
                        Latitude: '25.174878',
                        Longitude: '121.432739',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '44-205',
                        StationName: '台北內湖站',
                        StationTelephone: '02-2658-3366',
                        StationAddress: '11493 台北市內湖區內湖路一段236號',
                        StationType: '2',
                        Latitude: '25.082302',
                        Longitude: '121.565174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '52-206',
                        StationName: '台北南港站',
                        StationTelephone: '02-2651-1333',
                        StationAddress: '11568 台北市南港區經貿一路59號',
                        StationType: '2',
                        Latitude: '25.056168',
                        Longitude: '121.620091',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '85-208',
                        StationName: '台北新店站',
                        StationTelephone: '02-2915-3311',
                        StationAddress: '23143 新北市新店區北新路二段45號',
                        StationType: '2',
                        Latitude: '24.972855',
                        Longitude: '121.542796',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '115-905',
                        StationName: '台北板橋驛站',
                        StationTelephone: '02-2250-3131',
                        StationAddress: '220 新北市板橋區文化路二段266號',
                        StationType: '2',
                        Latitude: '25.028858',
                        Longitude: '121.471619',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '87-218',
                        StationName: '台北中和站',
                        StationTelephone: '02-2242-3232',
                        StationAddress: '23553 新北市中和區連城路126號',
                        StationType: '2',
                        Latitude: '24.999440',
                        Longitude: '121.495982',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '48-213',
                        StationName: '台北新莊站',
                        StationTelephone: '02-2906-7711',
                        StationAddress: '24257 新北市新莊區中正路527號',
                        StationType: '2',
                        Latitude: '25.033227',
                        Longitude: '121.439553',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '64-216',
                        StationName: '台北蘆洲站',
                        StationTelephone: '02-2285-2299',
                        StationAddress: '24760 新北市蘆洲區三民路88號',
                        StationType: '2',
                        Latitude: '25.085329',
                        Longitude: '121.473834',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '73-217',
                        StationName: '台北土城站',
                        StationTelephone: '02-2269-3131',
                        StationAddress: '23680 新北市土城區中央路三段158號',
                        StationType: '2',
                        Latitude: '24.965791',
                        Longitude: '121.432121',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '133-C016',
                        StationName: '元隆三峽站',
                        StationTelephone: '02-26731000',
                        StationAddress: '新北市三峽區復興路179-5號',
                        StationType: '7',
                        Latitude: '24.938647',
                        Longitude: '121.369003',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '147-C032',
                        StationName: '裕信新莊思源站',
                        StationTelephone: '02-89935288',
                        StationAddress: '新北市新莊區思源路40-1號',
                        StationType: '7',
                        Latitude: '25.042911',
                        Longitude: '121.460376',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '148-C033',
                        StationName: '裕信新店中興站',
                        StationTelephone: '02-89199922',
                        StationAddress: '新北市新店區中興路三段9號',
                        StationType: '7',
                        Latitude: '24.978081',
                        Longitude: '121.545325',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '149-C034',
                        StationName: '裕信汐止大同站',
                        StationTelephone: '02-26476565',
                        StationAddress: '新北市汐止區大同路一段199號',
                        StationType: '7',
                        Latitude: '25.057157',
                        Longitude: '121.633047',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '03',
                CityName: '基隆',
                StationInformation: [
                    {
                        StationCode: '36-219',
                        StationName: '台北松山機場站',
                        StationTelephone: '02-2715-1133',
                        StationAddress: '10548 台北市松山區敦化北路340之9號',
                        StationType: '2',
                        Latitude: '25.061978',
                        Longitude: '121.551995',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1930',
                        },
                    },
                    {
                        StationCode: '1-201',
                        StationName: '台北建北站',
                        StationTelephone: '02-2502-1389',
                        StationAddress: '10489 台北市中山區建國北路一段71-1號',
                        StationType: '2',
                        Latitude: '25.051158',
                        Longitude: '121.537153',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '2-202',
                        StationName: '台北忠孝站',
                        StationTelephone: '02-8785-6620',
                        StationAddress: '11062 台北市信義區忠孝東路五段705號',
                        StationType: '2',
                        Latitude: '25.042513',
                        Longitude: '121.580242',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '3-203',
                        StationName: '台北景美站',
                        StationTelephone: '02-8931-0266',
                        StationAddress: '11681 台北市文山區羅斯福路五段221號',
                        StationType: '2',
                        Latitude: '25.002065',
                        Longitude: '121.539165',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '4-204',
                        StationName: '台北士林站',
                        StationTelephone: '02-2835-1100',
                        StationAddress: '11158 台北市士林區德行西路81號',
                        StationType: '2',
                        Latitude: '25.104611',
                        Longitude: '121.521735',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '60-222',
                        StationName: '台北淡水站',
                        StationTelephone: '02-2629-9393',
                        StationAddress: '25155 新北市淡水區中正路1號',
                        StationType: '2',
                        Latitude: '25.174878',
                        Longitude: '121.432739',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '44-205',
                        StationName: '台北內湖站',
                        StationTelephone: '02-2658-3366',
                        StationAddress: '11493 台北市內湖區內湖路一段236號',
                        StationType: '2',
                        Latitude: '25.082302',
                        Longitude: '121.565174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '52-206',
                        StationName: '台北南港站',
                        StationTelephone: '02-2651-1333',
                        StationAddress: '11568 台北市南港區經貿一路59號',
                        StationType: '2',
                        Latitude: '25.056168',
                        Longitude: '121.620091',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '115-905',
                        StationName: '台北板橋驛站',
                        StationTelephone: '02-2250-3131',
                        StationAddress: '220 新北市板橋區文化路二段266號',
                        StationType: '2',
                        Latitude: '25.028858',
                        Longitude: '121.471619',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '48-213',
                        StationName: '台北新莊站',
                        StationTelephone: '02-2906-7711',
                        StationAddress: '24257 新北市新莊區中正路527號',
                        StationType: '2',
                        Latitude: '25.033227',
                        Longitude: '121.439553',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '64-216',
                        StationName: '台北蘆洲站',
                        StationTelephone: '02-2285-2299',
                        StationAddress: '24760 新北市蘆洲區三民路88號',
                        StationType: '2',
                        Latitude: '25.085329',
                        Longitude: '121.473834',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                ],
            },
            {
                CityCode: '04',
                CityName: '桃園',
                StationInformation: [
                    {
                        StationCode: '47-301',
                        StationName: '桃園復興站',
                        StationTelephone: '03-331-9555',
                        StationAddress: '33066 桃園市桃園區復興路325號',
                        StationType: '1',
                        Latitude: '24.989457',
                        Longitude: '121.304681',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '54-303',
                        StationName: '桃園中壢站',
                        StationTelephone: '03-462-9911',
                        StationAddress: '32069 桃園市中壢區中華路二段128號',
                        StationType: '1',
                        Latitude: '24.965971',
                        Longitude: '121.240613',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '6-302',
                        StationName: '桃園高鐵站',
                        StationTelephone: '03-261-1881',
                        StationAddress: '32056 桃園市中壢區青埔里高鐵北路一段6號',
                        StationType: '4',
                        Latitude: '25.012994',
                        Longitude: '121.214855',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '63-305',
                        StationName: '桃園大園站',
                        StationTelephone: '03-383-0123',
                        StationAddress: '33746 桃園市大園區三民路二段50之2號',
                        StationType: '1',
                        Latitude: '25.088166',
                        Longitude: '121.253158',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1930',
                        },
                    },
                    {
                        StationCode: '92-306',
                        StationName: '桃園機場站',
                        StationTelephone: '03-393-1133',
                        StationAddress: '33758桃園市大園區航站南路15號(一航廈內)',
                        StationType: '2',
                        Latitude: '25.079651',
                        Longitude: '121.234217',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1930',
                        },
                    },
                    {
                        StationCode: '134-C017',
                        StationName: '元隆桃園中山站',
                        StationTelephone: '03-3601119',
                        StationAddress: '桃園市桃園區中山路1310號',
                        StationType: '7',
                        Latitude: '24.979848',
                        Longitude: '121.273124',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '135-C018',
                        StationName: '元隆桃園楊梅站',
                        StationTelephone: '03-4752353',
                        StationAddress: '桃園市楊梅區中山北路一段75號',
                        StationType: '7',
                        Latitude: '24.907466',
                        Longitude: '121.151526',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '136-C019',
                        StationName: '元隆桃園蘆竹站',
                        StationTelephone: '03-3521122',
                        StationAddress: '桃園市蘆竹區南崁路二段180號',
                        StationType: '7',
                        Latitude: '25.058854',
                        Longitude: '121.275592',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '137-C020',
                        StationName: '元隆桃園平鎮站',
                        StationTelephone: '03-4644888',
                        StationAddress: '桃園市平鎮區延平路三段588號',
                        StationType: '7',
                        Latitude: '24.931757',
                        Longitude: '121.197195',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '138-C021',
                        StationName: '元隆桃園桃鶯站',
                        StationTelephone: '03-3752266',
                        StationAddress: '桃園市桃鶯路441號',
                        StationType: '7',
                        Latitude: '24.978300',
                        Longitude: '121.322251',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '139-C022',
                        StationName: '元隆桃園中壢站',
                        StationTelephone: '03-4598981',
                        StationAddress: '桃園市中壢區環中東路二段731號',
                        StationType: '7',
                        Latitude: '24.943075',
                        Longitude: '121.227730',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '140-C023',
                        StationName: '元隆桃園八德站',
                        StationTelephone: '03-3681111',
                        StationAddress: '桃園市八德區介壽路二段731號',
                        StationType: '7',
                        Latitude: '24.938388',
                        Longitude: '121.297678',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '141-C024',
                        StationName: '元隆桃園龍潭站',
                        StationTelephone: '03-4709359',
                        StationAddress: '桃園市龍潭區中豐路中山段206號',
                        StationType: '7',
                        Latitude: '24.866319',
                        Longitude: '121.210058',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '142-C025',
                        StationName: '元隆桃園北中壢站',
                        StationTelephone: '03-4527111',
                        StationAddress: '桃園市中壢區中園路170號',
                        StationType: '7',
                        Latitude: '24.973866',
                        Longitude: '121.236352',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '05',
                CityName: '新竹',
                StationInformation: [
                    {
                        StationCode: '7-311',
                        StationName: '新竹中華站',
                        StationTelephone: '03-515-3528',
                        StationAddress: '30060 新竹市東區中華路一段315號',
                        StationType: '2',
                        Latitude: '24.809473',
                        Longitude: '120.983936',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '8-312',
                        StationName: '新竹高鐵站',
                        StationTelephone: '03-612-5668',
                        StationAddress: '30273 新竹縣竹北市隘口里2鄰高鐵七路6號',
                        StationType: '4',
                        Latitude: '24.808192',
                        Longitude: '121.040225',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                ],
            },
            {
                CityCode: '06',
                CityName: '苗栗',
                StationInformation: [
                    {
                        StationCode: '7-311',
                        StationName: '新竹中華站',
                        StationTelephone: '03-515-3528',
                        StationAddress: '30060 新竹市東區中華路一段315號',
                        StationType: '2',
                        Latitude: '24.809473',
                        Longitude: '120.983936',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '8-312',
                        StationName: '新竹高鐵站',
                        StationTelephone: '03-612-5668',
                        StationAddress: '30273 新竹縣竹北市隘口里2鄰高鐵七路6號',
                        StationType: '4',
                        Latitude: '24.808192',
                        Longitude: '121.040225',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '78-307',
                        StationName: '苗栗高鐵站',
                        StationTelephone: '037-248-168',
                        StationAddress: '35648 苗栗縣後龍鎮高鐵三路268號',
                        StationType: '4',
                        Latitude: '24.605722',
                        Longitude: '120.825354',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0800',
                            EndTime: '2000',
                        },
                    },
                    {
                        StationCode: '70-405',
                        StationName: '台中中清站',
                        StationTelephone: '04-2426-1155',
                        StationAddress: '40761 台中市西屯區中清路二段1326號',
                        StationType: '1',
                        Latitude: '24.194637',
                        Longitude: '120.658957',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '9-401',
                        StationName: '台中朝馬站',
                        StationTelephone: '04-2253-1268',
                        StationAddress: '40757 台中市西屯區黎明路二段1024號、1026號',
                        StationType: '1',
                        Latitude: '24.169772',
                        Longitude: '120.636334',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '65-403',
                        StationName: '台中機場站',
                        StationTelephone: '04-2615-5233',
                        StationAddress: '43346 台中市沙鹿區中航路1段168號(入境大廳)',
                        StationType: '4',
                        Latitude: '24.254034',
                        Longitude: '120.600174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1900',
                        },
                    },
                    {
                        StationCode: '10-402',
                        StationName: '台中高鐵站',
                        StationTelephone: '04-3601-5775',
                        StationAddress: '41456 台中市烏日區三和里3鄰站區二路8號',
                        StationType: '4',
                        Latitude: '24.111616',
                        Longitude: '120.615738',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                ],
            },
            {
                CityCode: '07',
                CityName: '台中',
                StationInformation: [
                    {
                        StationCode: '70-405',
                        StationName: '台中中清站',
                        StationTelephone: '04-2426-1155',
                        StationAddress: '40761 台中市西屯區中清路二段1326號',
                        StationType: '1',
                        Latitude: '24.194637',
                        Longitude: '120.658957',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '9-401',
                        StationName: '台中朝馬站',
                        StationTelephone: '04-2253-1268',
                        StationAddress: '40757 台中市西屯區黎明路二段1024號、1026號',
                        StationType: '1',
                        Latitude: '24.169772',
                        Longitude: '120.636334',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '65-403',
                        StationName: '台中機場站',
                        StationTelephone: '04-2615-5233',
                        StationAddress: '43346 台中市沙鹿區中航路1段168號(入境大廳)',
                        StationType: '4',
                        Latitude: '24.254034',
                        Longitude: '120.600174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1900',
                        },
                    },
                    {
                        StationCode: '10-402',
                        StationName: '台中高鐵站',
                        StationTelephone: '04-3601-5775',
                        StationAddress: '41456 台中市烏日區三和里3鄰站區二路8號',
                        StationType: '4',
                        Latitude: '24.111616',
                        Longitude: '120.615738',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '117-C001',
                        StationName: '裕唐台中東區站',
                        StationTelephone: '04-22113939',
                        StationAddress: '401台中市東區振興路379-1號',
                        StationType: '7',
                        Latitude: '24.131341',
                        Longitude: '120.703576',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '118-C002',
                        StationName: '裕唐台中北區站',
                        StationTelephone: '04-22052929',
                        StationAddress: '404台中市北區中華路二段126號',
                        StationType: '7',
                        Latitude: '24.152538',
                        Longitude: '120.682473',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '119-C003',
                        StationName: '裕唐台中北屯站',
                        StationTelephone: '04-22470688',
                        StationAddress: '406台中市北屯區松竹路三段8號',
                        StationType: '7',
                        Latitude: '24.182058',
                        Longitude: '120.683147',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '120-C004',
                        StationName: '裕唐台中潭子站',
                        StationTelephone: '04-25320113',
                        StationAddress: '臺中市潭子區中山路三段438號',
                        StationType: '7',
                        Latitude: '24.234153',
                        Longitude: '120.709545',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '121-C005',
                        StationName: '裕唐台中沙鹿站',
                        StationTelephone: '04-26629811',
                        StationAddress: '433台中市沙鹿區台灣大道七段955號',
                        StationType: '7',
                        Latitude: '24.239500',
                        Longitude: '120.563809',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '122-C006',
                        StationName: '裕唐台中大甲站',
                        StationTelephone: '04-26860826',
                        StationAddress: '437台中市大甲區中山路一段972-2號',
                        StationType: '7',
                        Latitude: '24.351474',
                        Longitude: '120.628174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '123-C007',
                        StationName: '裕民台中文心站',
                        StationTelephone: '04-23129111',
                        StationAddress: '台中市西屯區文心路三段456號',
                        StationType: '7',
                        Latitude: '24.172359',
                        Longitude: '120.664399',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '08',
                CityName: '彰化',
                StationInformation: [
                    {
                        StationCode: '70-405',
                        StationName: '台中中清站',
                        StationTelephone: '04-2426-1155',
                        StationAddress: '40761 台中市西屯區中清路二段1326號',
                        StationType: '1',
                        Latitude: '24.194637',
                        Longitude: '120.658957',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '9-401',
                        StationName: '台中朝馬站',
                        StationTelephone: '04-2253-1268',
                        StationAddress: '40757 台中市西屯區黎明路二段1024號、1026號',
                        StationType: '1',
                        Latitude: '24.169772',
                        Longitude: '120.636334',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '65-403',
                        StationName: '台中機場站',
                        StationTelephone: '04-2615-5233',
                        StationAddress: '43346 台中市沙鹿區中航路1段168號(入境大廳)',
                        StationType: '4',
                        Latitude: '24.254034',
                        Longitude: '120.600174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1900',
                        },
                    },
                    {
                        StationCode: '10-402',
                        StationName: '台中高鐵站',
                        StationTelephone: '04-3601-5775',
                        StationAddress: '41456 台中市烏日區三和里3鄰站區二路8號',
                        StationType: '4',
                        Latitude: '24.111616',
                        Longitude: '120.615738',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '79-406',
                        StationName: '彰化高鐵站',
                        StationTelephone: '04-700-0168',
                        StationAddress: '52046 彰化縣田中鎮站區路二段99號',
                        StationType: '4',
                        Latitude: '23.874325',
                        Longitude: '120.574710',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0800',
                            EndTime: '2000',
                        },
                    },
                ],
            },
            {
                CityCode: '09',
                CityName: '南投',
                StationInformation: [
                    {
                        StationCode: '70-405',
                        StationName: '台中中清站',
                        StationTelephone: '04-2426-1155',
                        StationAddress: '40761 台中市西屯區中清路二段1326號',
                        StationType: '1',
                        Latitude: '24.194637',
                        Longitude: '120.658957',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '9-401',
                        StationName: '台中朝馬站',
                        StationTelephone: '04-2253-1268',
                        StationAddress: '40757 台中市西屯區黎明路二段1024號、1026號',
                        StationType: '1',
                        Latitude: '24.169772',
                        Longitude: '120.636334',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '65-403',
                        StationName: '台中機場站',
                        StationTelephone: '04-2615-5233',
                        StationAddress: '43346 台中市沙鹿區中航路1段168號(入境大廳)',
                        StationType: '4',
                        Latitude: '24.254034',
                        Longitude: '120.600174',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1900',
                        },
                    },
                    {
                        StationCode: '10-402',
                        StationName: '台中高鐵站',
                        StationTelephone: '04-3601-5775',
                        StationAddress: '41456 台中市烏日區三和里3鄰站區二路8號',
                        StationType: '4',
                        Latitude: '24.111616',
                        Longitude: '120.615738',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                ],
            },
            {
                CityCode: '10',
                CityName: '雲林',
                StationInformation: [
                    {
                        StationCode: '80-504',
                        StationName: '雲林高鐵站',
                        StationTelephone: '05-700-0168',
                        StationAddress: '63247 雲林縣虎尾鎮站前東路301號',
                        StationType: '4',
                        Latitude: '23.735708',
                        Longitude: '120.415979',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0800',
                            EndTime: '2000',
                        },
                    },
                    {
                        StationCode: '11-501',
                        StationName: '嘉義站',
                        StationTelephone: '05-227-8855',
                        StationAddress: '60049 嘉義市西區林森西路556號',
                        StationType: '1',
                        Latitude: '23.479794',
                        Longitude: '120.442375',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '13-503',
                        StationName: '嘉義高鐵站',
                        StationTelephone: '05-310-5225',
                        StationAddress: '61241 嘉義縣太保市高鐵西路168號',
                        StationType: '4',
                        Latitude: '23.455365',
                        Longitude: '120.323809',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                ],
            },
            {
                CityCode: '11',
                CityName: '嘉義',
                StationInformation: [
                    {
                        StationCode: '11-501',
                        StationName: '嘉義站',
                        StationTelephone: '05-227-8855',
                        StationAddress: '60049 嘉義市西區林森西路556號',
                        StationType: '1',
                        Latitude: '23.479794',
                        Longitude: '120.442375',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '13-503',
                        StationName: '嘉義高鐵站',
                        StationTelephone: '05-310-5225',
                        StationAddress: '61241 嘉義縣太保市高鐵西路168號',
                        StationType: '4',
                        Latitude: '23.455365',
                        Longitude: '120.323809',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                ],
            },
            {
                CityCode: '12',
                CityName: '台南',
                StationInformation: [
                    {
                        StationCode: '15-603',
                        StationName: '台南北門站',
                        StationTelephone: '06-223-5566',
                        StationAddress: '70449 台南市北區北門路二段111、113號',
                        StationType: '2',
                        Latitude: '22.999680',
                        Longitude: '120.212508',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '45-606',
                        StationName: '台南永康站',
                        StationTelephone: '06-243-6655',
                        StationAddress: '71081台南市永康區中正北路169號',
                        StationType: '1',
                        Latitude: '23.041863',
                        Longitude: '120.242809',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '16-604',
                        StationName: '台南高鐵站',
                        StationTelephone: '06-600-0006',
                        StationAddress: '71151 台南市歸仁區沙崙里9鄰歸仁大道100號',
                        StationType: '4',
                        Latitude: '22.924511',
                        Longitude: '120.285517',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '126-C009',
                        StationName: '國通台南永康永大站',
                        StationTelephone: '06-2020051#200',
                        StationAddress: '臺南市永康區永大路二段1296號',
                        StationType: '7',
                        Latitude: '23.021566',
                        Longitude: '120.261675',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '127-C010',
                        StationName: '國通台南新營站',
                        StationTelephone: '06-6561447#200',
                        StationAddress: '臺南市新營區民治路198號',
                        StationType: '7',
                        Latitude: '23.308806',
                        Longitude: '120.305262',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '128-C011',
                        StationName: '國通台南東區站',
                        StationTelephone: '06-2689943#200',
                        StationAddress: '臺南市東區中華東路三段151號',
                        StationType: '7',
                        Latitude: '22.977351',
                        Longitude: '120.226365',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '129-C012',
                        StationName: '國通台南佳里站',
                        StationTelephone: '06-7231002#200',
                        StationAddress: '臺南市佳里區民安里同安寮1-29號',
                        StationType: '7',
                        Latitude: '23.165285',
                        Longitude: '120.188345',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '130-C013',
                        StationName: '國通台南永康中華站',
                        StationTelephone: '06-2521560#200',
                        StationAddress: '臺南市永康區中華路995號',
                        StationType: '7',
                        Latitude: '23.022745',
                        Longitude: '120.219231',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '131-C014',
                        StationName: '國通台南善化站',
                        StationTelephone: '06-5812100#200',
                        StationAddress: '臺南市善化區興農路50號',
                        StationType: '7',
                        Latitude: '23.132851',
                        Longitude: '120.282272',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '132-C015',
                        StationName: '國通台南南區站',
                        StationTelephone: '06-2915011#200',
                        StationAddress: '臺南市南區中華西路一段79號',
                        StationType: '7',
                        Latitude: '22.975629',
                        Longitude: '120.183926',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '13',
                CityName: '高雄',
                StationInformation: [
                    {
                        StationCode: '18-702',
                        StationName: '高雄三多商圈站',
                        StationTelephone: '07-333-6161',
                        StationAddress: '80660 高雄市前鎮區中山二路70、72號',
                        StationType: '2',
                        Latitude: '22.609349',
                        Longitude: '120.306582',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '19-703',
                        StationName: '高雄建國站',
                        StationTelephone: '07-236-5510',
                        StationAddress: '80750 高雄市三民區建國二路264號',
                        StationType: '2',
                        Latitude: '22.637827',
                        Longitude: '120.304754',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '20-701',
                        StationName: '高雄小港機場站',
                        StationTelephone: '07-802-2148',
                        StationAddress: '81223 高雄市小港區中山四路2號(高雄國際航空站租車中心)',
                        StationType: '1',
                        Latitude: '22.570818',
                        Longitude: '120.342621',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2000',
                        },
                    },
                    {
                        StationCode: '90-701',
                        StationName: '高雄小港站',
                        StationTelephone: '07-802-5577',
                        StationAddress: '81257 高雄市小港區中山四路1、3號',
                        StationType: '1',
                        Latitude: '22.569242',
                        Longitude: '120.347960',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2000',
                        },
                    },
                    {
                        StationCode: '40-705',
                        StationName: '高雄左營站',
                        StationTelephone: '07-349-7808',
                        StationAddress: '81361 高雄市左營區重信路615號',
                        StationType: '5',
                        Latitude: '22.686027',
                        Longitude: '120.308299',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '21-705',
                        StationName: '左營高鐵站',
                        StationTelephone: '07-349-7808',
                        StationAddress: '81361 高雄市左營區高鐵路105號',
                        StationType: '4',
                        Latitude: '22.687135',
                        Longitude: '120.307658',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0700',
                            EndTime: '2200',
                        },
                    },
                    {
                        StationCode: '42-706',
                        StationName: '高雄鳳山站',
                        StationTelephone: '07-767-6699',
                        StationAddress: '83048 高雄市鳳山區建國路三段378號',
                        StationType: '1',
                        Latitude: '22.638000',
                        Longitude: '120.348739',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '145-C028',
                        StationName: '裕昌高雄左營站',
                        StationTelephone: '07-3462555',
                        StationAddress: '高雄市左營區大中一路399號',
                        StationType: '7',
                        Latitude: '22.677565',
                        Longitude: '120.321127',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0900',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '14',
                CityName: '屏東',
                StationInformation: [
                    {
                        StationCode: '22-801',
                        StationName: '屏東站',
                        StationTelephone: '08-751-6688',
                        StationAddress: '90085 屏東縣屏東市建國路298號',
                        StationType: '1',
                        Latitude: '22.664685',
                        Longitude: '120.471545',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                ],
            },
            {
                CityCode: '15',
                CityName: '宜蘭',
                StationInformation: [
                    {
                        StationCode: '57-231',
                        StationName: '宜蘭羅東站',
                        StationTelephone: '03-960-2116',
                        StationAddress: '26561 宜蘭縣羅東鎮光榮路334號',
                        StationType: '2',
                        Latitude: '24.678464',
                        Longitude: '121.778003',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '143-C026',
                        StationName: '元隆宜蘭羅東站',
                        StationTelephone: '03-9530123',
                        StationAddress: '宜蘭縣羅東鎮純精路三段416號',
                        StationType: '7',
                        Latitude: '24.686416',
                        Longitude: '121.768687',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                    {
                        StationCode: '144-C027',
                        StationName: '元隆宜蘭宜興站',
                        StationTelephone: '03-9289989',
                        StationAddress: '宜蘭縣宜蘭市宜興路三段28號',
                        StationType: '7',
                        Latitude: '24.766623',
                        Longitude: '121.761460',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'N',
                            isRentalAtHome: 'N',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '1730',
                        },
                    },
                ],
            },
            {
                CityCode: '16',
                CityName: '花蓮',
                StationInformation: [
                    {
                        StationCode: '23-821',
                        StationName: '花蓮站',
                        StationTelephone: '03-831-6688',
                        StationAddress: '97055 花蓮縣花蓮市國聯一路117號',
                        StationType: '1',
                        Latitude: '23.990667',
                        Longitude: '121.602229',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                    {
                        StationCode: '74-822',
                        StationName: '花蓮玉里站',
                        StationTelephone: '03-888-8787',
                        StationAddress: '98142 花蓮縣玉里鎮大同路174號',
                        StationType: '2',
                        Latitude: '23.329865',
                        Longitude: '121.312383',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                ],
            },
            {
                CityCode: '17',
                CityName: '台東',
                StationInformation: [
                    {
                        StationCode: '24-831',
                        StationName: '台東站',
                        StationTelephone: '089-227-979',
                        StationAddress: '95058 台東縣台東市新站路243號',
                        StationType: '2',
                        Latitude: '22.792513',
                        Longitude: '121.124800',
                        ReservationCondition: {
                            InAdvanceHours: '24',
                            isAccesssary: 'Y',
                            isRentalAtHome: 'Y',
                        },
                        BussinessHours: {
                            StartTime: '0830',
                            EndTime: '2030',
                        },
                    },
                ],
            },
        ],
    };
}
